name: coffee_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/sbuc.jpg
    - assets/cake_coffee.jpg
    - assets/dalgona_coffee.jpeg
    - assets/user_profile.jpg
    

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf

  uses-material-design: true
